name: ML-Train mit Performance-Report
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert

      - name: 'Prepare data'
        run: |
          jupyter nbconvert --to script data/dataprep_scripts/dataprep_git.ipynb 
          python data/dataprep_scripts/dataprep_git.py 

      - name: Generate and publish plots Data Tests
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          # Generiere einen Report der einzigartig ist um nicht immer den gleichen Report zu erhalten
          report_file="report_data_plots.md"

          # Read the column names from the CSV file
          columns=$(head -n 1 data/column_source_csv/source.csv | tr ',' '\n')
      
          # Iterate over each column
          for column in $columns; do
            # Update the report
            echo "\n## Datenvisualisierung fÃ¼r $column" >> $report_file
          
            cml-publish data/plot_data/${column}.png --md >> $report_file
          done
      
          cml-send-comment $report_file
          
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jupyter nbconvert --to script model/ml_model_scripts/pytorch_train.ipynb
          python model/ml_model_scripts/pytorch_train.py

          echo "## Model Metriken" > report_ml.md
          cat model/metrics/metrics.txt >> report_ml.md
          
          echo "\n## Model Performance" >> report_ml.md
          echo "Modell Performance bzw. das Matching zwischen Predictions und True-Labels in einer Heatmap dargestellt!" >> report_ml.md
          cml-publish model/plots/heatmap.jpg --md >> report_ml.md
          
          echo "\n## Model Performance" >> report_ml.md
          echo "Modell Performance in einem Scatter-Plot dargestellt" >> report_ml.md
          cml-publish model/plots/plot_scatter.jpg --md >> report_ml.md
        
          echo "\n## Model Performance" >> report_ml.md
          echo "Modell Performance in einem normalen Plot dargestellt" >> report_ml.md
          cml-publish model/plots/plot_plt.jpg --md >> report_ml.md
      
          cml-send-comment report_ml.md

      - name: Commit and push model from train.py
        run: |
          git config --local user.email "Aseuc@github.com"
          git config --local user.name "Aseuc"
          git add .
          git commit -m "Add generated file" -a || echo "No changes to commit"
          git push origin test_torch-new-workflow  
  



      
          